<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NeoArchiveAI.Domain\NeoArchiveAI.Domain.csproj" />
    <ProjectReference Include="..\NeoArchiveAI.Application\NeoArchiveAI.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
